import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Top Headlines",
  description: "Generated by create next app",
  icons: {
    icon: "/newspaper.ico",
    shortcut: "/newspaper.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className="font-serif bg-black text-white"
      >
        {children}
      </body>
    </html>
  );
}
