import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Top Headlines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" type="image/x-icon" href="/globe.svg" />
      <body
        className="font-serif bg-black text-white"
      >
        {children}
      </body>
    </html>
  );
}
